table train
	lineageTag: 6d341a6d-b6a8-46d5-ab40-59b640e2d349

	column PassengerId
		dataType: int64
		formatString: 0
		lineageTag: d5e5e6b5-9f8c-4dd7-972c-35f0fd72a274
		summarizeBy: count
		sourceColumn: PassengerId

		annotation SummarizationSetBy = Automatic

	column Survived
		dataType: int64
		formatString: 0
		lineageTag: a7627c2a-d97f-4c47-a8bd-b27d4ec92680
		summarizeBy: sum
		sourceColumn: Survived

		annotation SummarizationSetBy = Automatic

	column Pclass
		dataType: int64
		formatString: 0
		lineageTag: 8da23d08-36fd-42f0-bc29-aa86e6973018
		summarizeBy: sum
		sourceColumn: Pclass

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 6352aff2-6957-49a4-9893-3d8191d28ae2
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Sex
		dataType: string
		lineageTag: 1a49556b-5d40-4013-a97c-09f041e365b1
		summarizeBy: none
		sourceColumn: Sex

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: double
		lineageTag: cb4e9eed-21b6-4b9c-a486-cd8c097e2136
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SibSp
		dataType: int64
		formatString: 0
		lineageTag: 7e051896-de1d-4937-afce-37dbccc8d8ee
		summarizeBy: sum
		sourceColumn: SibSp

		annotation SummarizationSetBy = Automatic

	column Parch
		dataType: int64
		formatString: 0
		lineageTag: 309d5bd3-18cc-4fe2-b854-f1e278375fa5
		summarizeBy: sum
		sourceColumn: Parch

		annotation SummarizationSetBy = Automatic

	column Ticket
		dataType: string
		lineageTag: df2b5093-e3ce-4e13-8dac-4233b7a98088
		summarizeBy: none
		sourceColumn: Ticket

		annotation SummarizationSetBy = Automatic

	column Fare
		dataType: double
		lineageTag: e9b5c6e9-e8eb-48fe-93e8-58203e212254
		summarizeBy: sum
		sourceColumn: Fare

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Cabin
		dataType: string
		lineageTag: 307022a7-f0d9-4fed-b3e1-2647ee38e0aa
		summarizeBy: none
		sourceColumn: Cabin

		annotation SummarizationSetBy = Automatic

	column Embarked
		dataType: string
		lineageTag: 6a51ebdf-2064-4c56-9554-15c4e96706e8
		summarizeBy: none
		sourceColumn: Embarked

		annotation SummarizationSetBy = Automatic

	partition train = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\jsingh5\OneDrive - Covalience, LLC\Documents\Data Science\PowerBi\PowerBiTraining-\train.csv"),[Delimiter=",", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"PassengerId", Int64.Type}, {"Survived", Int64.Type}, {"Pclass", Int64.Type}, {"Name", type text}, {"Sex", type text}, {"Age", type number}, {"SibSp", Int64.Type}, {"Parch", Int64.Type}, {"Ticket", type text}, {"Fare", type number}, {"Cabin", type text}, {"Embarked", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

